#server.port=8060
#spring.application.name=proxyservices
#eureka.client.fetchRegistry=true
#zuul.routes.reservation-business-service.path=/reservation/**
#zuul.routes.reservation-business-service.service-id=RESERVATIONBUSINESSSERVICES
#zuul.sensitive-headers=Cookie,Set-Cookie
##Ribbon is auto integrated with Zuul and for this exercise we are not using that.
#ribbon.eureka.enabled=true

server:
  port: ${PORT:8060}
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: proxyservices
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
zuul:
  ignoredServices: "*"
  routes:
    reservation-business-service:
      path: /reservation/**
      serviceId: RESERVATIONBUSINESSSERVICES
  add-proxy-headers: true
  sensitive-headers: Cookie,Set-Cookie

ribbon:
  eureka:
    enabled: true
  ConnectTimeout:  10000
  ReadTimeout:  10000
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: proxyservices