#management.endpoints.web.exposure.include=hystrix.stream
#spring.main.allow-bean-definition-overriding=true
#
#keycloak.auth-server-url=http://prg03.kevuru.com:8181/auth
#keycloak.realm=ReservationService
#keycloak.resource=login-app
#keycloak.public-client=true
#keycloak.principal-attribute=preferred_username
#keycloak.security-constraints[0].authRoles[0]=user
##keycloak.security-constraints[0].securityCollections[0].patterns[0]=/rooms/*
#cors: true  # solves front-end CORS issue in browser
#ssl-required: none
#confidential-port: 0
keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: ReservationService
  resource: login-app
  public-client: true
  principal-attribute: preferred_username
  ssl-required: none
  confidential-port: 0
  bearer-only: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

spring:
  main:
    allow-bean-definition-overriding: true
